TRUNCATE TABLE  categories CASCADE;
TRUNCATE TABLE  registrations CASCADE;
TRUNCATE TABLE  events CASCADE;
TRUNCATE TABLE  users CASCADE;
TRUNCATE TABLE  locations CASCADE;
TRUNCATE TABLE  roles CASCADE;